package com.producer.orders_producer_service.service;

import com.salinda.kafka.avro.Order; // Generated by Avro
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.util.Random;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class OrderProducerService {


    private final KafkaTemplate<String, Order> kafkaTemplate;
    private final Random random = new Random();
    private final String[] products = {"Laptop", "Mouse", "Keyboard", "Monitor", "Headset"};


    @Value("${application.kafka.topic}")
    private String topicName;

    public void sendOrder(Order order) {

        var future = kafkaTemplate.send(topicName, order.getOrderId().toString(), order);

        future.whenComplete((result, exception) -> {
            if (exception == null) {
                System.out.println(" Successfully sent order: " + order.getOrderId());
            } else {
                System.err.println(" Failed to send order: " + order.getOrderId());
                exception.printStackTrace();
            }
        });
    }

    @Scheduled(fixedRate = 3000)
    public void generateAndSendOrder() {
        // 1. Generate Data
        String orderId = UUID.randomUUID().toString();
        String product = products[random.nextInt(products.length)];
        float price = 10.0f + random.nextFloat() * 90.0f;

        // 2. Create Object
        Order order = Order.newBuilder()
                .setOrderId(orderId)
                .setProduct(product)
                .setPrice(price)
                .build();
        // 3. Send Order
        sendOrder(order);
    }
}
